config/routes.rb
Rails.application.routes.draw do


  post  'users/:id/update'  => 'users#update'
  get   'users/:id/edit'    => 'users#edit'
  post  'users/create'      => 'users#create'
  get   'users/new'         => 'users#new'
  get   'users/index'       => 'users#index'
  
  post  'users/login'       => 'users#login'
  post  'users/logout'      => 'users#logout'
  get   'users/login'       => 'users#login_form'
  get   'users/:id'         => 'users#show'
  get   'users/:id/likes'   => 'users#likes'

  get   '/users/:id/following(.:format)' => 'users#following'
  get   '/users/:id/followers(.:format)' => 'users#followers'
  get   '/users/stats'      => 'users#stats'

  get   'posts/index'       => 'posts#index'
  get   'posts/new'         => 'posts#new'
  post  'posts/create'      => 'posts#create'
  get   'posts/:id'         => 'posts#show'
  get   'posts/:id/edit'    => 'posts#edit'
  post  'posts/:id/update'  => 'posts#update'
  post  'posts/:id/destroy' => 'posts#destroy'

  post  'likes/:post_id/create' => 'likes#create'
  post  'likes/:post_id/destroy'=> 'likes#destroy'

  get   '/'                 => 'home#top'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
    validates :user_id, {presence: true}
    validates :post_id, {presence: true}
end

app/models/poel.rb
class Poel < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord

    validates :title, {presence: true}
    validates :content, {presence: true}

    def user
        return User.find_by(id: self.user_id)
      end
      


end

app/models/user.rb
class User < ApplicationRecord

    validates :name, {presence: true}
    validates :email, {presence: true, uniqueness: true}
    validates :password, {presence: true}


    def posts
        return Post.where(user_id: self.id)
      end

      has_many :relationships
      has_many :followings, through: :relationships, source: :follow
      has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
      has_many :followers, through: :reverse_of_relationships, source: :user

      def follow(other_user)
        unless self == other_user
          self.relationships.find_or_create_by(follow_id: other_user.id)
        end
      end
    
      def unfollow(other_user)
        relationship = self.relationships.find_by(follow_id: other_user.id)
        relationship.destroy if relationship
      end
    
      def following?(other_user)
        self.followings.include?(other_user)
      end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :set_current_user


  
    def set_current_user
      
      @current_user = User.find_by(id: session[:user_id])
    end
    
    def authenticate_user
      if @current_user == nil
        flash[:notice] = "ログインが必要です"
        redirect_to("/users/login")
      end
    end
    
    def forbid_login_user
      if @current_user
        flash[:notice] = "すでにログインしています"
        redirect_to("/posts/index")
      end
    end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end
  def about
  end
  def contact
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user
  before_action :ensure_correct_user, {only: [:edit, :update, :destroy]}


  def index
    @posts= Post.all.order(created_at: :desc)
  end

  def show
    @post = Post.find_by(id: params[:id])
    @user = @post.user
    @likes_count = Like.where(post_id: @post.id).count
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(title: params[:title],
                     content: params[:content],
                     user_id: @current_user.id)
     if @post.save
          flash[:notice] = "post crear"
          redirect_to("/posts/index")
     else
          render 'new'
     end
  end

  

  def edit
    @post = Post.find_by(id: params[:id])
  end

  def update
    @post = Post.find_by(id: params[:id])
    @post.title = params[:title]
    @post.content = params[:content]
    if @post.save
       redirect_to("/posts/index")
    else
      render("/posts/edit")
    end
  end

  def destroy
    @post = Post.find_by(id: params[:id])
    @post.destroy
    redirect_to("/posts/index")
  end

  def ensure_correct_user
    @post = Post.find_by(id: params[:id])
    if @post.user_id != @current_user.id
      flash[:notice] = "権限がありません"
      redirect_to("/posts/index")
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user, {only: [:index, :show, :edit, :update]}
  before_action :forbid_login_user, {only: [:new, :create, :login_form, :login]}
  before_action :ensure_correct_user, {only: [:edit, :update]}


  def index
    @users = User.all
  end

  def show
    @user = User.find_by(id: params[:id])
  end

  def new
    @user = User.new
    
  end

  def create
    @user = User.new(
      name: params[:name],
      email:params[:email],
      password: params[:password],
      image_name: "default_user.jpg"
    )
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "success signup"
      redirect_to("/users/#{@user.id}")
    else
      render('users/new')
    end
  end

  def edit
    @user = User.find_by(id: params[:id])
  end

  def update
    @user = User.find_by(id: params[:id])
    @user.name = params[:name]
    @user.email = params[:email]

    if params[:image]
      @user.image_name = "#{@user.id}.jpg"
      image = params[:image]
      File.binwrite("public/user_images/#{@user.image_name}", image.read)
      
    end

    if @user.save
      redirect_to("/users/#{@user.id}")
    else
      render('users/edit')
    end
  end

  def login_form
  end

  def login
    @user = User.find_by(email: params[:email],password: params[:password])
    if @user
      session[:user_id] = @user.id
      redirect_to('/posts/index')
    else
      render('users/login_form')
    end
  end

  def logout
    session[:user_id] = nil
    redirect_to("/users/login")
  end

  def likes
    @user = User.find_by(id: params[:id])
    @likes = Like.where(user_id: @user.id)
  end

  

  def following
    @user  = User.find(params[:id])
    @users = @user.following
    render 'show_follow'
  end

  def followers
    @user  = User.find(params[:id])
    @users = @user.followers
    render 'show_follower'
  end

  def stats
  end



  def ensure_correct_user
    if @current_user.id != params[:id].to_i
      flash[:notice] = "権限がありません"
      redirect_to("/posts/index")
    end
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/about.html.erb
<div>
  <h1> about Page </h1>
</div>

app/views/home/contact.html.erb
<div>
  <h1>contact Page</h2>
  </div>

app/views/home/top.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div>
      <h1>hello world</h1>
        <%= link_to("SignUp","/users/new") %>
        <%= link_to("Login","/users/login") %>
        <%= link_to("Posts","/posts/index") %>
    </div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | Ruby on Rails Tutorial Sample App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">

  </head>

  <body>
  <div class="home">
    <header>
      <div class="header-logo">
        <% if @current_user %>
          <%= link_to("テクトレ", "/posts/index") %>
        <% else %>
          <%= link_to("テクトレ", "/") %>
        <% end %>
      </div>
      <ul class="header-menus">
        <% if @current_user %>
          
          <li>
            <%= link_to("投稿一覧", "/posts/index") %>
          </li>
          <li>
            <%= link_to("新規投稿", "/posts/new") %>
          </li>
          <li>
            <%= link_to("ユーザー一覧", "/users/index") %>
          </li>
          <li>
            <%= link_to("ログアウト", "/users/logout", {method: :post}) %>
          </li>
        <% else %>
          <li>
            <%= link_to("TweetAppとは", "/about") %>
          </li>
          <li>
            <%= link_to("新規登録", "/users/new") %>
          </li>
          <li>
            <%= link_to("ログイン", "/users/login") %>
          </li>
        <% end %>
      </ul>

    </header>


    <div class="content">
    
    <div class="side">
      
      <% if @current_user %>
        <ul>
           <div class= "user">
            <img src="<%= "/user_images/#{@current_user.image_name}" %>">
            </div>
        <li>
            <%= link_to(@current_user.name, "/users/#{@current_user.id}") %>
        </li>
        <li>
            <%= link_to("ログアウト", "/users/logout", {method: :post}) %>
          </li>
        <ul>
        <% else %>
        <ul>
         <li> noimage </li>
         <li> guest </li>
          
        </ul>
        <% end %>
    </div>
  

    
      <%= yield %>
    </div>
    <footer class="footer">
    <nav>
    <ul>
      <li><%= link_to "About", "/home/about" %></li>
      <li><%= link_to "Contact", "/home/about" %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
    </nav>

    </footer>
  </div>
  </body>

</html>

app/views/posts/edit.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>edit画面</h1>
    <%= form_tag("/posts/#{@post.id}/update") do %>
    <input name = "title" value="<%= @post.title %>">
    <textarea name="content"><%= @post.content %></textarea>
    <input type="submit">
    <%end%>
</body>
</html>

app/views/posts/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div>
      <%= link_to("new","/posts/new") %>
      <h1> post 一覧　</h1>
       
       <% @posts.each do |post| %>
         <div>
            ---------------------<br>
            <div class="show_image">
              <img src="<%= "/user_images/#{post.user.image_name}" %>">

            </div>
            <%= link_to(post.title,"/posts/#{post.id}") %><br>
            <%= post.content %> 
            
         </div>
         <%end%>

    </div>
</body>
</html>

app/views/posts/new.html.erb
<% provide(:title, 'Sign up') %>

<div>
<h1>投稿画面です</h1>
<%= form_tag("/posts/create") do %>
  <h2>Title</h2>
 <input type="text" name="title">
  <h2>Contents</h2>
  <textarea name="content"></textarea>
  <input type="submit">
  <%end%>
</div>
    

app/views/posts/show.html.erb
<%= @post.id %>
<div class = "post-time">
<%= @post.created_at %>
</div>
<%= @post.title %><br>
<%= @post.content %><br>
<%= link_to("edit","/posts/#{@post.id}/edit") %>
<%= link_to("deleate","/posts/#{@post.id}/destroy",{method:"post"}) %>


<% if Like.find_by(user_id: @current_user.id, post_id: @post.id) %>
        <%= link_to("/likes/#{@post.id}/destroy", {method: "post"}) do %>
          <span class="fa fa-heart like-btn-unlike"></span>
        <% end %>
      <% else %>
        <%= link_to("/likes/#{@post.id}/create", {method: "post"}) do %>
          <span class="fa fa-heart like-btn"></span>
        <% end %>
      <% end %>

  <%= @likes_count %>

 

app/views/users/_follow.html.erb

<div>

    <%= form_for(current_user.active_relationships.build) do |f| %>
  <div><%= hidden_field_tag :following_id, @user.id %></div>
     <%= f.submit "Follow", class: "btn btn-primary" %>
    <% end %>

</div>

app/views/users/_follow_from.html.erb

<div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>

app/views/users/_unfollow.html.erb
<div>

    <%= form_for(current_user.active_relationships.find_by(following_id: @user.id),
             html: { method: :delete }) do |f| %>
    <%= f.submit "Unfollow", class: "btn" %>
    <% end %>


</div>

app/views/users/edit.html.erb


  <div>
    <%= form_tag("/users/#{@user.id}/update",{multipart: true}) do %>
      <h2>name</h2>
       <input name="name" value="<%= @user.name %>">
      <h2>email</h2>
       <input name="email" value="<%= @user.email %>">
       <h2>image</h2>
       <input name="image" type="file">
       <input type="submit">
    <% end %>



  </div>

app/views/users/index.html.erb
<div>


  <% @users.each do |user| %>
   <div class ="user">
    <img src="<%= "/user_images/#{user.image_name}" %>"><br>
    <%= link_to(user.name, "/users/#{user.id}") %><br>
    <%= user.email %>
    <p>-------------------------------</p>
    </div>
  <% end %>

</div>

app/views/users/likes.html.erb
<div class = "main user-show">

<h1>
      Userの詳細画面<br>
      <img src="<%= "/user_images/#{@user.image_name}" %>"><br>
      <%= @user.name %><br>
      <%= @user.email %>
    </h1>

    <%= link_to("user編集","/users/#{@user.id}/edit") %>



<ul class="user-tabs">
      <li><%= link_to("投稿", "/users/#{@user.id}") %></li>
      <li class="active"><%= link_to("いいね!", "/users/#{@user.id}/likes") %></li>
    </ul>

 <% @likes.each do |like| %>

  <% post = Post.find_by(id: like.post_id) %>

  <div>
  <div>
    <img src="<%= "/user_images/#{post.user.image_name}" %>">

  </div>
    <%= link_to(post.user.name, "/users/#{post.user.id}")%>
    <%= link_to(post.title, "/posts/#{post.id}") %>
    <%= post.content %>
  </div>
   <%end%>

</div>

app/views/users/login_form.html.erb


    <div>
      <h1>Login</h1>
      <%= form_tag("/users/login") do %>
      
        <h2>user email</h2>
         <input type="text" name="email">
         <h2>user password</h2>
         <input type="password" name="password">
         <input type="submit">
         <% end %>
    </div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>    
    
    <div>
      <h1>user signup</h1>
       <%= form_tag("/users/create") do %>
        <h2>user name</h2>
         <input type="text" name="name" value="<%= @user.name %>">
        <h2>user email</h2>
         <input type="text" name="email" value="<%= @user.email %>">
        <h2>user password</h2>
         <input type="password" name="password">
         
         <input type="submit">
        <% end %>

    </div>
   

app/views/users/show.html.erb

  
  <div class = "user">

    <h1>
      Userの詳細画面<br>
      <img src="<%= "/user_images/#{@user.image_name}" %>"><br>
      <%= @user.name %><br>
      <%= @user.email %>
    </h1>


    <% if @user %>
     <div id="follow_form">
      <% if @current_user.following?(@user) %>
        <%= render 'unfollow' %>
      <% else %>
        <%= render 'follow' %>
      <% end %>
      </div>
    <% end %>


<a href="<%= following_user_path(@user) %>">
  <%= @user.following.count %>
following
</a>
<a href="<%= followers_user_path(@user) %>">
  <%= @user.followers.count %>
followers
</a>
     
    
    <%= link_to("user編集","/users/#{@user.id}/edit") %>

    <ul class="user-tabs">
      <li><%= link_to("投稿", "/users/#{@user.id}") %></li>
      <li class="active"><%= link_to("いいね!", "/users/#{@user.id}/likes") %></li>
    </ul>

    <% @user.posts.each do |post| %>
     <div>
        <div>
          <img src="<%= "/user_images/#{post.user.image_name}" %>">
        </div>
        <div>
          <%= link_to(post.user.name, "/users/#{post.user.id}") %>
        </div>
          <%= link_to(post.title, "/posts/#{post.id}") %>
          <%= post.content %>
     </div>
     <% end %>

  </div>

app/views/users/show_follow.html.erb
<% @user.following.each do |user| %>
<table>
<tr>
  <td>  <%= user.name %> </td>
  <td><%= link_to '詳細', user_path(user) %></td>
</tr>

</table>
<% end %>

app/views/users/show_follower.html.erb
<% @user.followers.each do |user| %>
<table>
<tr>
  <td>  <%= user.name %> </td>
  <td><%= link_to '詳細', user_path(user) %></td>
</tr>

</table>
<% end %>

app/views/users/stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>